name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # запуск каждые 5 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.CHAT_ID }}&text=/ping"
